CREATE TABLE PRODUCT (
PRODUCT_ID VARCHAR2(20) CONSTRAINT PRO_ID_PK PRIMARY KEY,
P_NAME VARCHAR2(40) NOT NULL,
PRICE VARCHAR(20) NOT NULL,
DESCRIPTION VARCHAR2(200),
STOCK NUMBER NOT NULL
);

SELECT * FROM PRODUCT;
COMMENT ON COLUMN PRODUCT.PRODUCT_ID IS '상품아이디';
COMMENT ON COLUMN PRODUCT.P_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT.PRICE IS '상품가격';
COMMENT ON COLUMN PRODUCT.DESCRIPTION IS '상품상세정보';
COMMENT ON COLUMN PRODUCT.STOCK IS '재고';

INSERT INTO PRODUCT VALUES('nb_ss7','삼성노트북','1570000','시리즈7',10);
INSERT INTO PRODUCT VALUES('nb_ama4','맥북에어','1200000','xcode4',20);
INSERT INTO PRODUCT VALUES('pc_ibm','ibmpc','75000','window8',5);

commit;