CREATE TABLE PRODUCT_IO(
IO_NUM NUMBER PRIMARY KEY,
PRODUCT_ID VARCHAR2(20) REFERENCES PRODUCT ON DELETE CASCADE,
IO_DATE DATE DEFAULT SYSDATE NOT NULL,
AMOUNT NUMBER NOT NULL,
STATUS VARCHAR(15) CHECK(STATUS IN('입고','출고'))
);
CREATE SEQUENCE SEQ_IO_NUM;

CREATE OR REPLACE TRIGGER PRODUCT
AFTER INSERT ON PRODUCT_IO
FOR EACH ROW
BEGIN
IF:NEW.STATUS = '입고'
THEN 
    UPDATE PRODUCT 
    SET STOCK = STOCK + :NEW.AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END IF; 

IF:NEW.STATUS='출고'
THEN
    UPDATE PRODUCT
    SET STOCK = STOCK - :NEW.AMOUNT
    WHERE PRODUCT_ID = :NEW.PRODUCT_ID;
END IF;
END; 
/
commit;

INSERT INTO PRODUCT_IO VALUES(SEQ_IO_NUM.NEXTVAL, 'nb_ss7', '19/07/01', 30, '입고');
INSERT INTO PRODUCT_IO VALUES(SEQ_IO_NUM.NEXTVAL, 'nb_ss7', '19/07/02', 3, '출고');
INSERT INTO PRODUCT_IO VALUES(SEQ_IO_NUM.NEXTVAL, 'pc_ibm', '19/07/02', 10, '입고');

commit;

SELECT IO_NUM, I.PRODUCT_ID,P_NAME,IO_DATE,AMOUNT,PRICE FROM PRODUCT_IO I, PRODUCT P WHERE I.PRODUCT_ID  = P.PRODUCT_ID;

SELECT IO_NUM,PRODUCT_ID,P_NAME,IO_DATE,AMOUNT,STATUS FROM PRODUCT_IO JOIN PRODUCT USING(PRODUCT_ID) WHERE STATUS='입고';

SELECT IO_NUM,PRODUCT_ID,P_NAME,IO_DATE,AMOUNT,STATUS FROM PRODUCT_IO JOIN PRODUCT USING(PRODUCT_ID) WHERE STATUS='출고';